//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Account {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.LinkButton lbtnAccount;
	
	protected System.Web.UI.WebControls.LinkButton lbtnStats;
	
	protected System.Web.UI.WebControls.HyperLink hlEarningArea;
	
	protected System.Web.UI.WebControls.Panel AccountInfo;
	
	protected System.Web.UI.WebControls.FormView fvUserImage;
	
	protected System.Web.UI.WebControls.Image Image1;
	
	protected System.Web.UI.WebControls.TextBox txtUserName;
	
	protected System.Web.UI.WebControls.TextBox txtIP;
	
	protected System.Web.UI.WebControls.TextBox txtGender;
	
	protected System.Web.UI.WebControls.TextBox txtDateOfBirth;
	
	protected System.Web.UI.WebControls.TextBox txtEmail;
	
	protected System.Web.UI.WebControls.TextBox txtNewEmail;
	
	protected System.Web.UI.WebControls.TextBox txtPassword;
	
	protected System.Web.UI.WebControls.TextBox txtPaypalEmail;
	
	protected System.Web.UI.WebControls.TextBox txtPasswordQuestion;
	
	protected System.Web.UI.WebControls.TextBox txtPasswordAnswer;
	
	protected System.Web.UI.WebControls.TextBox txtPhone;
	
	protected System.Web.UI.WebControls.TextBox txtAddress;
	
	protected System.Web.UI.WebControls.Panel Stats;
	
	protected System.Web.UI.WebControls.TextBox txtBalance;
	
	protected System.Web.UI.WebControls.TextBox txtAdsClicked;
	
	protected System.Web.UI.WebControls.TextBox txtPendingWithdrawl;
	
	protected System.Web.UI.WebControls.TextBox txtPaymentsReceived;
	
	protected System.Web.UI.WebControls.TextBox txtPaymentsCancelled;
}
