//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Ads {
	
	protected System.Web.UI.WebControls.Content HeaderContent;
	
	protected System.Web.UI.WebControls.Content BodyContent;
	
	protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
	
	protected System.Web.UI.WebControls.Label lblMessage;
	
	protected System.Web.UI.WebControls.DropDownList ddlAdsPackage;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator rfvAdsPackage;
	
	protected System.Web.UI.WebControls.TextBox txtAdsName;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator rfvAdsName;
	
	protected System.Web.UI.WebControls.TextBox txtAdsDescription;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator rfvAdsDescription;
	
	protected System.Web.UI.WebControls.TextBox txtAdsURL;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator rfvAdsURL;
	
	protected System.Web.UI.WebControls.TextBox txtAdsClicksLeft;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator rfvAdsClicksLeft;
	
	protected System.Web.UI.WebControls.Button butSave;
	
	protected System.Web.UI.WebControls.Button butCancel;
	
	protected System.Web.UI.WebControls.GridView gvAds;
	
	protected System.Web.UI.WebControls.Label lblAdsPackage;
	
	protected System.Web.UI.WebControls.Label lblAdsName;
	
	protected System.Web.UI.WebControls.Label lblAdsDescription;
	
	protected System.Web.UI.WebControls.HyperLink HyperLink1;
	
	protected System.Web.UI.WebControls.Label lblAdsClicksLeft;
	
	protected System.Web.UI.WebControls.ImageButton ibutSelect;
	
	protected System.Web.UI.WebControls.ImageButton ibutDelete;
}
