//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class AdsPackage {
	
	protected System.Web.UI.WebControls.Content HeaderContent;
	
	protected System.Web.UI.WebControls.Content BodyContent;
	
	protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
	
	protected System.Web.UI.WebControls.Label lblMessage;
	
	protected System.Web.UI.WebControls.TextBox txtClicks;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator rfvClicks;
	
	protected System.Web.UI.WebControls.TextBox txtPrice;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator rfvPrice;
	
	protected System.Web.UI.WebControls.TextBox txtPerClick;
	
	protected System.Web.UI.WebControls.Button butSave;
	
	protected System.Web.UI.WebControls.Button butCancel;
	
	protected System.Web.UI.WebControls.GridView gvAdsPackage;
	
	protected System.Web.UI.WebControls.Label lblClicks;
	
	protected System.Web.UI.WebControls.Label lblPrice;
	
	protected System.Web.UI.WebControls.Label lblPerClick;
	
	protected System.Web.UI.WebControls.ImageButton ibutSelect;
	
	protected System.Web.UI.WebControls.ImageButton ibutDelete;
}
