//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class DefaultCapt {
	
	protected System.Web.UI.HtmlControls.HtmlForm form1;
	
	protected System.Web.UI.WebControls.TextBox txtCaptcha;
	
	protected System.Web.UI.WebControls.Button Button1;
}
