//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class ViewAds {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.GridView gvAds;
	
	protected System.Web.UI.WebControls.Label lblAdsName;
	
	protected System.Web.UI.WebControls.Label lblAdsDescription;
	
	protected System.Web.UI.WebControls.HyperLink HyperLink1;
	
	protected System.Web.UI.WebControls.Label lblPerClick;
}
